import '../styles/globals.css'
import Head from 'next/head'
import Navbar from './components/navbar'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Louis Teilliais - Site Personel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Louis.png" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
